name: bankr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  url_launcher: ^5.4.5
  http: ^0.12.0
  provider: ^4.0.5+1
  sembast: ^2.4.3
  path_provider: ^0.5.0+1
  flutter_web_auth: ^0.2.2
  dio: ^3.0.9
  shared_preferences: ^0.5.7+2
  flutter_secure_storage: ^3.3.3
  flutter_svg: ^0.17.4
  intl: ^0.16.1
  local_auth: ^0.6.2+3
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  uuid: 2.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  mockito: ^4.1.1
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/test/tl_account.json
    - assets/test/tl_account_balance.json
    - assets/test/tl_account_transaction.json
    - assets/test/access_token.json
    - assets/providers/monzo.svg
    - assets/providers/santander.svg